feat: dashboards
flojoy-ai/cloud pull request #81
Opened 2024-04-11 21:38 UTC by 39bytes

2024-04-15 18:11 UTC, LatentDream requested changes
## Product Testing feedback
- [x] TBD, the home page of a workspace: I think having `Product Lines | Inventory | Dashboard | Settings` on the same line / format would be better than the button.
  - Maybe workspace Settings could go in the dropdown when we click on the user profile ? ~ Might lead to confusion between global and workspace settings tho.
- Dashboard page
    - [x] Remove the `bruh` from the generated data.
    - [x] Add breadcrumb to easily understand that we are in the dashboard.
    - [x] Add sessions in generated data so the sessions overtime graph is not empty.
- Production Line page:
    - [ ] (Can be done later) The CSS overflows with half screen view.
    - [ ] (Only a suggestion) Hover over card with the "full description" of the docs for each metric.
- The Unit page where there is: `All tests that have been performed on "..." are listed here.`
    - [ ] The list points to Test session, not "tests". Change this in the subtitle.
    - [ ] Convert the User ID to user name or email.
    - [ ] User column title -> Operator.
    - [ ] Formatting the date? Could be in another issue, but it would looks 100000x better :)
- Test Result Metrics:
    - [ ] Add generated data for the metrics (so the graph is not empty when someone is looking at the demo).
    - [ ] The page "test/test_id" doesn't have a breadcrumb. Not sure what should be the order in it though.
- Station Page:
    - [ ] Let's remove the "Global Statistics" placeholder.
- [ ] Let's convert "Production Line" to "Test Profile" in the UI. That slight change will help for the demo a lot (since they are using this term everywhere).
    - I'll do the same in the Sequencer

2024-04-16 00:31 UTC, LatentDream approved these changes
**Feature wise**: All requirements are there :)

2024-04-16 12:15 UTC, itsjoeoui approved these changes
lgtm

2024-04-16 12:17 UTC, itsjoeoui requested changes

2024-04-16 12:17 UTC, itsjoeoui commented on apps/server/migrations/0010_session.ts
> +    .addColumn("duration_ms", "integer", (col) => col.notNull())
could you add the schema change to a separate file and use `alterTable`. This way we no longer drop the tables.

2024-04-16 15:01 UTC, itsjoeoui approved these changes
lgtm

2024-04-16 15:03 UTC, merged